# Global parameters
[global]
	netbios name = AD
	realm = CDPNI.SAP
	workgroup = CDPNI
	dns forwarder = 10.14.29.12
	server role = active directory domain controller
	idmap_ldb:use rfc2307 = yes
	
[homes]
	path = /srv/cdpni/homes/%S
	browseable = No
	read only = No

[printers]
	path = /var/spool/samba
	read only = No
	browseable = Yes
	printable = Yes

[print$]
	path = /srv/cdpni/samba/drivers
	read only = No
	browseable = No

[publico]
	path = /srv/cdpni/samba/publico
	read only = No
	guest ok = Yes
	force create mode = 644
	force directory mode = 755
	veto files = /*.mp3/*.mpeg/*.avi/*.mpg/*.exe/
	hide files = /*.ini/*.log/
	
[financas]
        path = /srv/cdpni/samba/owner
        read only = No
        guest ok = No
        force create mode = 644
        force directory mode = 755
        valid users = analista
        write list = analista
        max connections = 10
        veto files = /*.mp3/*.mpeg/*.avi/*.mpg/*.exe/*.iso/
        hide files = /*.ini/*.log/*.swp/*.tmp/

[nucleo_de_pessoal]
	path = /srv/cdpni/samba/security
	read only = No
	force create mode = 644
	force directory mode = 755
	veto files = /*.mp3/*.mpeg/*.avi/*.mpg/*.exe/*.iso/
	hide files = /*.ini/*.log/*.swp/*.tmp/
	hosts allow = 192.168.1.0/24 127.0.0.1

[infraestrutura]
	path = /srv/cdpni/samba/infrastrutura
	read only = No
	force create mode = 644
	force directory mode = 755
	veto files = /*.mp3/*.mpeg/*.avi/*.mpg/*.exe/*.iso/
	hide files = /*.ini/*.log/*.swp/*.tmp/

[administrativo]
	path = /srv/cdpnif/samba/administrativo
	read only = No
	force create mode = 644
	force directory mode = 755
	veto files = /*.mp3/*.mpeg/*.avi/*.mpg/*.exe/*.iso/
	hide files = /*.ini/*.log/*.swp/*.tmp/

[saude]
	path = /srv/cdpni/samba/saude
	read only = No
	force create mode = 644
	force directory mode = 755
	veto files = /*.mp3/*.mpeg/*.avi/*.mpg/*.exe/*.iso/
	hide files = /*.ini/*.log/*.swp/*.tmp/

[lixeiras]
	path = /srv/cdpni/samba/lixeiras
	browseable = No
	guest ok = Yes
	read only = No

[netlogon]
	path = /var/lib/samba/sysvol/cdpni.sap/scripts
	read only = No

[sysvol]
	path = /var/lib/samba/sysvol
	read only = No
